<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-09-21 05:51
=======
# Generated by Django 5.2.7 on 2025-10-06 13:15
>>>>>>> ff811a720dd096ebf10bc7783119920e5861e0d6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0004_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative'), ('O+', 'O positive'), ('O-', 'O negative')], max_length=5, null=True),
        ),
    ]
