# Generated by Django 5.2.3 on 2026-03-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physioapp', '0005_alter_patientprofile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
